import type { Metadata } from "next";
import Logo from './logo';
import "./globals.css";

export const metadata: Metadata = {
  title: "YAMI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <div className="m-4"><Logo /></div>
        <div className="">{children}</div>
      </body>
    </html>
  );
}
